<?php

namespace Shura\CSS\Color;

class Name
{
    private static $from_name = [
        'black' => '#000000',
        'silver' => '#c0c0c0',
        'gray' => '#808080',
        'white' => '#ffffff',
        'maroon' => '#800000',
        'red' => '#ff0000',
        'purple' => '#800080',
        'fuchsia' => '#ff00ff',
        'green' => '#008000',
        'lime' => '#00ff00',
        'olive' => '#808000',
        'yellow' => '#ffff00',
        'navy' => '#000080',
        'blue' => '#0000ff',
        'teal' => '#008080',
        'aqua' => '#00ffff',
        'orange' => '#ffa500',
        'aliceblue' => '#f0f8ff',
        'antiquewhite' => '#faebd7',
        'aquamarine' => '#7fffd4',
        'azure' => '#f0ffff',
        'beige' => '#f5f5dc',
        'bisque' => '#ffe4c4',
        'blanchedalmond' => '#ffebcd',
        'blueviolet' => '#8a2be2',
        'brown' => '#a52a2a',
        'burlywood' => '#deb887',
        'cadetblue' => '#5f9ea0',
        'chartreuse' => '#7fff00',
        'chocolate' => '#d2691e',
        'coral' => '#ff7f50',
        'cornflowerblue' => '#6495ed',
        'cornsilk' => '#fff8dc',
        'crimson' => '#dc143c',
        'cyan' => '#00ffff',
        'darkblue' => '#00008b',
        'darkcyan' => '#008b8b',
        'darkgoldenrod' => '#b8860b',
        'darkgray' => '#a9a9a9',
        'darkgreen' => '#006400',
        'darkgrey' => '#a9a9a9',
        'darkkhaki' => '#bdb76b',
        'darkmagenta' => '#8b008b',
        'darkolivegreen' => '#556b2f',
        'darkorange' => '#ff8c00',
        'darkorchid' => '#9932cc',
        'darkred' => '#8b0000',
        'darksalmon' => '#e9967a',
        'darkseagreen' => '#8fbc8f',
        'darkslateblue' => '#483d8b',
        'darkslategray' => '#2f4f4f',
        'darkslategrey' => '#2f4f4f',
        'darkturquoise' => '#00ced1',
        'darkviolet' => '#9400d3',
        'deeppink' => '#ff1493',
        'deepskyblue' => '#00bfff',
        'dimgray' => '#696969',
        'dimgrey' => '#696969',
        'dodgerblue' => '#1e90ff',
        'firebrick' => '#b22222',
        'floralwhite' => '#fffaf0',
        'forestgreen' => '#228b22',
        'gainsboro' => '#dcdcdc',
        'ghostwhite' => '#f8f8ff',
        'gold' => '#ffd700',
        'goldenrod' => '#daa520',
        'greenyellow' => '#adff2f',
        'grey' => '#808080',
        'honeydew' => '#f0fff0',
        'hotpink' => '#ff69b4',
        'indianred' => '#cd5c5c',
        'indigo' => '#4b0082',
        'ivory' => '#fffff0',
        'khaki' => '#f0e68c',
        'lavender' => '#e6e6fa',
        'lavenderblush' => '#fff0f5',
        'lawngreen' => '#7cfc00',
        'lemonchiffon' => '#fffacd',
        'lightblue' => '#add8e6',
        'lightcoral' => '#f08080',
        'lightcyan' => '#e0ffff',
        'lightgoldenrodyellow' => '#fafad2',
        'lightgray' => '#d3d3d3',
        'lightgreen' => '#90ee90',
        'lightgrey' => '#d3d3d3',
        'lightpink' => '#ffb6c1',
        'lightsalmon' => '#ffa07a',
        'lightseagreen' => '#20b2aa',
        'lightskyblue' => '#87cefa',
        'lightslategray' => '#778899',
        'lightslategrey' => '#778899',
        'lightsteelblue' => '#b0c4de',
        'lightyellow' => '#ffffe0',
        'limegreen' => '#32cd32',
        'linen' => '#faf0e6',
        'mediumaquamarine' => '#66cdaa',
        'mediumblue' => '#0000cd',
        'mediumorchid' => '#ba55d3',
        'mediumpurple' => '#9370db',
        'mediumseagreen' => '#3cb371',
        'mediumslateblue' => '#7b68ee',
        'mediumspringgreen' => '#00fa9a',
        'mediumturquoise' => '#48d1cc',
        'mediumvioletred' => '#c71585',
        'midnightblue' => '#191970',
        'mintcream' => '#f5fffa',
        'mistyrose' => '#ffe4e1',
        'moccasin' => '#ffe4b5',
        'navajowhite' => '#ffdead',
        'oldlace' => '#fdf5e6',
        'olivedrab' => '#6b8e23',
        'orangered' => '#ff4500',
        'orchid' => '#da70d6',
        'palegoldenrod' => '#eee8aa',
        'palegreen' => '#98fb98',
        'paleturquoise' => '#afeeee',
        'palevioletred' => '#db7093',
        'papayawhip' => '#ffefd5',
        'peachpuff' => '#ffdab9',
        'peru' => '#cd853f',
        'pink' => '#ffc0cb',
        'plum' => '#dda0dd',
        'powderblue' => '#b0e0e6',
        'rosybrown' => '#bc8f8f',
        'royalblue' => '#4169e1',
        'saddlebrown' => '#8b4513',
        'salmon' => '#fa8072',
        'sandybrown' => '#f4a460',
        'seagreen' => '#2e8b57',
        'seashell' => '#fff5ee',
        'sienna' => '#a0522d',
        'skyblue' => '#87ceeb',
        'slateblue' => '#6a5acd',
        'slategray' => '#708090',
        'slategrey' => '#708090',
        'snow' => '#fffafa',
        'springgreen' => '#00ff7f',
        'steelblue' => '#4682b4',
        'tan' => '#d2b48c',
        'thistle' => '#d8bfd8',
        'tomato' => '#ff6347',
        'turquoise' => '#40e0d0',
        'violet' => '#ee82ee',
        'wheat' => '#f5deb3',
        'whitesmoke' => '#f5f5f5',
        'yellowgreen' => '#9acd32',
        'rebeccapurple' => '#663399',
        'transparent' => 'rgba(0,0,0,0)'
    ];

    private static $from_color_1 = [
        '000000' => 'black',
        'c0c0c0' => 'silver',
        '808080' => 'gray',
        'ffffff' => 'white',
        '800000' => 'maroon',
        'ff0000' => 'red',
        '800080' => 'purple',
        'ff00ff' => 'fuchsia',
        '008000' => 'green',
        '00ff00' => 'lime',
        '808000' => 'olive',
        'ffff00' => 'yellow',
        '000080' => 'navy',
        '0000ff' => 'blue',
        '008080' => 'teal',
        '00ffff' => 'aqua',
    ];

    private static $from_color_2 = [
        'ffa500' => 'orange',
    ];

    private static $from_color_3 = [
        '00ffff' => 'cyan',
        'f0f8ff' => 'aliceblue',
        'faebd7' => 'antiquewhite',
        '7fffd4' => 'aquamarine',
        'f0ffff' => 'azure',
        'f5f5dc' => 'beige',
        'ffe4c4' => 'bisque',
        'ffebcd' => 'blanchedalmond',
        '8a2be2' => 'blueviolet',
        'a52a2a' => 'brown',
        'deb887' => 'burlywood',
        '5f9ea0' => 'cadetblue',
        '7fff00' => 'chartreuse',
        'd2691e' => 'chocolate',
        'ff7f50' => 'coral',
        '6495ed' => 'cornflowerblue',
        'fff8dc' => 'cornsilk',
        'dc143c' => 'crimson',
        '00008b' => 'darkblue',
        '008b8b' => 'darkcyan',
        'b8860b' => 'darkgoldenrod',
        'a9a9a9' => 'darkgray',
        '006400' => 'darkgreen',
        'bdb76b' => 'darkkhaki',
        '8b008b' => 'darkmagenta',
        '556b2f' => 'darkolivegreen',
        'ff8c00' => 'darkorange',
        '9932cc' => 'darkorchid',
        '8b0000' => 'darkred',
        'e9967a' => 'darksalmon',
        '8fbc8f' => 'darkseagreen',
        '483d8b' => 'darkslateblue',
        '2f4f4f' => 'darkslategray',
        '00ced1' => 'darkturquoise',
        '9400d3' => 'darkviolet',
        'ff1493' => 'deeppink',
        '00bfff' => 'deepskyblue',
        '696969' => 'dimgray',
        '1e90ff' => 'dodgerblue',
        'b22222' => 'firebrick',
        'fffaf0' => 'floralwhite',
        '228b22' => 'forestgreen',
        'dcdcdc' => 'gainsboro',
        'f8f8ff' => 'ghostwhite',
        'ffd700' => 'gold',
        'daa520' => 'goldenrod',
        'adff2f' => 'greenyellow',
        'f0fff0' => 'honeydew',
        'ff69b4' => 'hotpink',
        'cd5c5c' => 'indianred',
        '4b0082' => 'indigo',
        'fffff0' => 'ivory',
        'f0e68c' => 'khaki',
        'e6e6fa' => 'lavender',
        'fff0f5' => 'lavenderblush',
        '7cfc00' => 'lawngreen',
        'fffacd' => 'lemonchiffon',
        'add8e6' => 'lightblue',
        'f08080' => 'lightcoral',
        'e0ffff' => 'lightcyan',
        'fafad2' => 'lightgoldenrodyellow',
        'd3d3d3' => 'lightgray',
        '90ee90' => 'lightgreen',
        'ffb6c1' => 'lightpink',
        'ffa07a' => 'lightsalmon',
        '20b2aa' => 'lightseagreen',
        '87cefa' => 'lightskyblue',
        '778899' => 'lightslategray',
        'b0c4de' => 'lightsteelblue',
        'ffffe0' => 'lightyellow',
        '32cd32' => 'limegreen',
        'faf0e6' => 'linen',
        '66cdaa' => 'mediumaquamarine',
        '0000cd' => 'mediumblue',
        'ba55d3' => 'mediumorchid',
        '9370db' => 'mediumpurple',
        '3cb371' => 'mediumseagreen',
        '7b68ee' => 'mediumslateblue',
        '00fa9a' => 'mediumspringgreen',
        '48d1cc' => 'mediumturquoise',
        'c71585' => 'mediumvioletred',
        '191970' => 'midnightblue',
        'f5fffa' => 'mintcream',
        'ffe4e1' => 'mistyrose',
        'ffe4b5' => 'moccasin',
        'ffdead' => 'navajowhite',
        'fdf5e6' => 'oldlace',
        '6b8e23' => 'olivedrab',
        'ff4500' => 'orangered',
        'da70d6' => 'orchid',
        'eee8aa' => 'palegoldenrod',
        '98fb98' => 'palegreen',
        'afeeee' => 'paleturquoise',
        'db7093' => 'palevioletred',
        'ffefd5' => 'papayawhip',
        'ffdab9' => 'peachpuff',
        'cd853f' => 'peru',
        'ffc0cb' => 'pink',
        'dda0dd' => 'plum',
        'b0e0e6' => 'powderblue',
        'bc8f8f' => 'rosybrown',
        '4169e1' => 'royalblue',
        '8b4513' => 'saddlebrown',
        'fa8072' => 'salmon',
        'f4a460' => 'sandybrown',
        '2e8b57' => 'seagreen',
        'fff5ee' => 'seashell',
        'a0522d' => 'sienna',
        '87ceeb' => 'skyblue',
        '6a5acd' => 'slateblue',
        '708090' => 'slategray',
        'fffafa' => 'snow',
        '00ff7f' => 'springgreen',
        '4682b4' => 'steelblue',
        'd2b48c' => 'tan',
        'd8bfd8' => 'thistle',
        'ff6347' => 'tomato',
        '40e0d0' => 'turquoise',
        'ee82ee' => 'violet',
        'f5deb3' => 'wheat',
        'f5f5f5' => 'whitesmoke',
        '9acd32' => 'yellowgreen',
    ];

    private static $from_color_4 = [ // not a standard
        '663399' => 'rebeccapurple',
    ];

    public static function fromColor(Color $color, bool $lts = false)
    {
        $hex = mb_strtolower(preg_replace('/^#/', '', $color->toHex(false)), 'UTF-8');

        if ($lts) {
            return isset(self::$from_color_1[$hex]) ? self::$from_color_1[$hex] : null;
        } else {
            for ($i = 1; $i <= 3; $i++) {
                if (isset(self::${"from_color_$i"}[$hex])) {
                    return self::${"from_color_$i"}[$hex];
                }
            }
            return null;
        }
    }

    public static function toColor(string $color)
    {
        $color = mb_strtolower(trim($color), 'UTF-8');

        return isset(self::$from_name[$color]) ? self::$from_name[$color] : null;
    }
}
